// import { Inter } from "next/font/google";

import SideBar from "@/components/UI/sidebar";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Obi | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={inter.className}
        className="bg-gradient-to-r from-emerald-600 to-blue-300"
      >
        <div className="relative z-40">
          <SideBar />
        </div>

        {children}
      </body>
    </html>
  );
}
