import React from "react";
import About from "../../../components/about/about";

export const metadata = {
  title: "Obi | About",
  description: "Generated by create next app",
};

const AboutMe = () => {
  return (
    <div>
      <About />
    </div>
  );
};

export default AboutMe;
