import Navbar from "@/components/header/navbar";

export const metadata = {
  title: "Obi | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children, // will be a page or nested layout
}) {
  return (
    <section>
      {/* Include shared UI here e.g. a header or sidebar */}
      <div className="relative z-10">
        <Navbar />
      </div>

      {children}
    </section>
  );
}
